spring:
  application:
    name: base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: qwer135!@
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true # sql ? ?? jpql ??????  ???? ??

#      sql:
#        init:
#          schema-locations: classpath:h2/schema.sql
#          data-locations: classpath:h2/data.sql

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  paths-to-match: /api/**



#  api-docs:
#    path: /v3/api-docs
#  paths-to-match: /api/**



#springdoc:
#  default-consumes-media-type: application/json;charset=UTF-8
#  default-produces-media-type: application/json;charset=UTF-8
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
