spring:
  application:
    name: base
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: test
    password: qwer135!@
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true # sql ? ?? jpql ??????  ???? ??
#  sql:
#    init:
#      schema-locations: classpath:h2/schema.sql
#      data-locations: classpath:h2/data.sql
  # H2 Setting Info (H2 Console? ???? ?? ???? ??)
#  h2:
#    console:
#      enabled: true  # H2 Console? ???? ?? (H2 Console? H2 Database? UI? ????? ??)
#      path: /h2-console  # H2 Console? Path