-- 테이블 생성 SQL - USER
CREATE TABLE USER_INFO
(
    `USER_SEQ`   INT             NOT NULL    AUTO_INCREMENT COMMENT '사용자 INDEX. 사용자 INDEX',
    `LOGIN_ID`   VARCHAR(50)     NOT NULL    COMMENT '로그인 아이디. 로그인 아이디',
    `PASSWORD`   VARCHAR(200)    NOT NULL    COMMENT '비밀번호. 비밀번호',
    `USER_NAME`  VARCHAR(50)     NOT NULL    COMMENT '사용자 이름. 사용자 이름',
    PRIMARY KEY (USER_SEQ)
);

-- Index 설정 SQL - USER(LOGIN_ID)
CREATE INDEX IX_USER_1
    ON USER_INFO(LOGIN_ID);

-- 테이블 생성 SQL - LOGIN_HISTORY
CREATE TABLE LOGIN_HISTORY
(
    `LOGIN_HISTORY_SEQ`  INT          NOT NULL    AUTO_INCREMENT COMMENT '로그인 이력 INDEX',
    `USER_SEQ`           INT          NOT NULL    COMMENT '사용자 INDEX',
    `LOGIN_AT`           TIMESTAMP    NOT NULL    COMMENT '로그인 시간',
    PRIMARY KEY (LOGIN_HISTORY_SEQ)
);

-- Index 설정 SQL - LOGIN_HISTORY(LOGIN_AT)
CREATE INDEX IX_LOGIN_HISTORY_1
    ON LOGIN_HISTORY(LOGIN_AT DESC);

-- 외래키 설정 SQL - LOGIN_HISTORY(USER_SEQ)
ALTER TABLE `LOGIN_HISTORY`
    ADD CONSTRAINT FK_LOGIN_HISTORY_USER FOREIGN KEY (USER_SEQ) REFERENCES USER_INFO(USER_SEQ)
        ON DELETE CASCADE  -- 사용자 삭제 시 로그인 기록도 삭제